services:
  backend:
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2G

  n8n:
    restart: always
    ports: []
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G

  frontend:
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
